# Generated by Django 5.0.4 on 2024-04-16 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_account_rename_quantity_cart_quantity_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='account',
            new_name='amount',
        ),
    ]
